# Prebuild script: gzips the config-page HTML (src/webui.html) and emits a
# gzipped copy as src/webui_html_gz.h. The device serves the gzip payload
# (Content-Encoding: gzip) instead of ~93KB of raw HTML, which cuts page
# transfer time several-fold on slow clients and frees ~75KB of flash.
import gzip
import os

Import("env")

PROJECT_DIR = env.subst("$PROJECT_DIR")
SRC = os.path.join(PROJECT_DIR, "src", "webui.html")
HDR = os.path.join(PROJECT_DIR, "src", "webui_html_gz.h")


def main():
    if not os.path.exists(SRC):
        print("[gzip_webui] %s not found, skipping" % SRC)
        return
    with open(SRC, "rb") as f:
        raw = f.read()
    # Normalize line endings so the gzip output is deterministic.
    html = raw.replace(b"\r\n", b"\n")
    gz = gzip.compress(html, 9)
    with open(HDR, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/gzip_webui.py - do not edit.\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write("static const uint8_t index_html_gz[] = {\n  ")
        for i, b in enumerate(gz):
            if i % 16 == 0 and i != 0:
                f.write("\n  ")
            f.write("0x%02X," % b)
        f.write("\n};\n")
        f.write("static const uint32_t index_html_gz_len = %d;\n" % len(gz))
    print("[gzip_webui] HTML %d -> gzip %d bytes (%d%% saved)" %
          (len(html), len(gz), 100 - (100 * len(gz) // len(html))))


main()