#!/usr/bin/env python3
"""Issue #21: regenerate the FIRMWARE_LIMITS block in src/webui.html.

The bands live in src/config.cpp (one source of truth, enforced on every write
path). The WebUI needs the same numbers to show min/max hints and to clamp a
value before posting it, so this script copies them out of the config table
between the BEGIN/END FIRMWARE_LIMITS markers. Values are in metric units, the
same units the firmware stores.

Run from the repository root:
    python scripts/make_webui_limits.py
Then rebuild the firmware so the gzip'd copy of the WebUI is regenerated.
"""
import re

CFG = "src/config.cpp"
UI = "src/webui.html"

num = r"[-+0-9.eEfF]+"
sym = r"[-+0-9.eEfFA-Z_]+"

header = open("src/dashboard.h", encoding="utf-8").read()
consts = {m.group(1): float(m.group(2))
          for m in re.finditer(r"constexpr\s+\w+\s+([A-Z0-9_]+)\s*=\s*([0-9.eE+]+)UL?;",
                               header)}

text = open(CFG, encoding="utf-8").read()
call = re.compile(
    r"(?m)^\s*CFG_(INT|UINT|FLT)\(\s*([A-Z0-9_]+)\s*,\s*\"([^\"]+)\"\s*,\s*"
    r"(" + num + r")\s*,\s*(" + sym + r")\s*,\s*(" + sym + r")\s*\);", re.S)


def resolve(expr):
    try:
        return float(expr.rstrip("f"))
    except ValueError:
        return consts[expr]


def fmt(v):
    if v == int(v):
        return str(int(v))
    return repr(v)


rows = []
for kind, name, nvs, dflt, lo, hi in call.findall(text):
    rows.append((name, fmt(resolve(lo)), fmt(resolve(hi))))

body = ["// BEGIN FIRMWARE_LIMITS (generated by scripts/make_webui_limits.py - do not edit)"]
body.append("// Allowed band [min, max] for every numeric config parameter, in"
            " metric units.")
body.append("// The firmware clamps out-of-range values on load and on save"
            " (issue #21); this table")
body.append("// exists so the WebUI can show the band and fix the value before"
            " posting it.")
body.append("const FIRMWARE_LIMITS = {")
for name, lo, hi in rows:
    body.append("    %s: [%s, %s]," % (name, lo, hi))
body.append("};")
body.append("// END FIRMWARE_LIMITS")
block = "\n".join(body)

ui = open(UI, encoding="utf-8").read()
pat = re.compile(r"// BEGIN FIRMWARE_LIMITS.*?// END FIRMWARE_LIMITS", re.S)
if pat.search(ui):
    ui = pat.sub(lambda m: block, ui, count=1)
else:
    anchor = "// Config fields whose values are unit-dependent, and their unit type."
    assert anchor in ui, "anchor for the limits block is missing"
    ui = ui.replace(anchor, block + "\n\n" + anchor, 1)

open(UI, "w", encoding="utf-8", newline="").write(ui)
print("wrote %d parameter bands into %s" % (len(rows), UI))
