#!/usr/bin/env python3
"""Issue #21: regenerate the FIRMWARE_LIMITS block in src/webui.html.

The bands live in src/config.cpp (one source of truth, enforced on every write
path). The WebUI needs the same numbers to show min/max hints and to clamp a
value before posting it, so this script copies them out of the config table
between the BEGIN/END FIRMWARE_LIMITS markers. Values are in metric units, the
same units the firmware stores.

Since the CFG_* macros became the CFG_TABLE rows (one row per parameter, all
kinds), the bands come from those rows: lo/hi for CK_INT and CK_UINT, flo/fhi for
CK_FLT. CK_BOOL / CK_STR / CK_SECRET rows carry no band and are skipped. Row
order is preserved, which is the order the WebUI lists its fields in.

Run from the repository root:
    python scripts/make_webui_limits.py
Then rebuild the firmware so the gzip'd copy of the WebUI is regenerated.
"""
import re
import sys

from cfg_table import config_text, fmt_number, numeric_rows

UI = "src/webui.html"

try:
    rows = [(name, fmt_number(lo), fmt_number(hi))
            for name, _kind, lo, hi, _d in numeric_rows(config_text())]
except KeyError as e:
    sys.exit("band references a constant this script cannot resolve: %s" % e)

body = ["// BEGIN FIRMWARE_LIMITS (generated by scripts/make_webui_limits.py - do not edit)"]
body.append("// Allowed band [min, max] for every numeric config parameter, in"
            " metric units.")
body.append("// The firmware clamps out-of-range values on load and on save"
            " (issue #21); this table")
body.append("// exists so the WebUI can show the band and fix the value before"
            " posting it.")
body.append("const FIRMWARE_LIMITS = {")
for name, lo, hi in rows:
    body.append("    %s: [%s, %s]," % (name, lo, hi))
body.append("};")
body.append("// END FIRMWARE_LIMITS")
block = "\n".join(body)

ui = open(UI, encoding="utf-8", newline="").read()
pat = re.compile(r"// BEGIN FIRMWARE_LIMITS.*?// END FIRMWARE_LIMITS", re.S)
if pat.search(ui):
    ui = pat.sub(lambda m: block, ui, count=1)
else:
    anchor = "// Config fields whose values are unit-dependent, and their unit type."
    assert anchor in ui, "anchor for the limits block is missing"
    ui = ui.replace(anchor, block + "\n\n" + anchor, 1)

open(UI, "w", encoding="utf-8", newline="").write(ui)
print("wrote %d parameter bands into %s" % (len(rows), UI))
