#!/usr/bin/env python3
"""Release signing tool for the Dashboard++ cloud OTA pull (SECURITY plan 2).

The firmware verifies every pulled image against a public key compiled into it
(src/otasign.cpp, include/ota_pubkey.h). This script owns the other half: the
private key, and the signature asset that ships next to the firmware binary.

SCHEME (must stay byte-identical with src/otasign.cpp)

    payload   = sha256(firmware.bin) as 32 RAW bytes
              + 0x0A
              + version string, UTF-8            (exactly as the release tag,
                                                  less any leading v/V)
    signature = ECDSA (curve P-256) over SHA-256(payload), in the standard
                  DER ECDSA-Sig-Value encoding openssl produces (~71-72 bytes)

Binding the version into the signature is what stops a manifest that keeps a
valid signed binary but rewrites the version (or serves an old signed release
again under a new label). The download URL is deliberately NOT in the payload:
swapping the URL changes the bytes, which changes the digest, which fails
verification anyway.

Why ECDSA P-256 and not Ed25519: the mbedTLS build shipped with Arduino core
3.3.12 has no Ed25519 (verified against libmbedcrypto.a - zero ed25519
symbols), and enabling it would mean rebuilding the framework. ECDSA P-256 +
SHA-256 is compiled in and in the same 128-bit security class.

Open source stays open: the public key is committed (include/ota_pubkey.h),
anyone can fork, build and flash their own image over USB (the serial path and
the Web UI upload path are unsigned by design), and anyone can generate their
own keypair and swap the header. The private key only decides what THIS unit's
cloud pull will accept.

USAGE
    python scripts/ota_sign.py keygen            # once; never lose the key
    python scripts/ota_sign.py pubkey            # refresh include/ota_pubkey.h
    python scripts/ota_sign.py sign 1.3.9 .pio/build/esp32dev/firmware.bin
    python scripts/ota_sign.py verify 1.3.9 .pio/build/esp32dev/firmware.bin
"""

import hashlib
import os
import subprocess
import sys

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY_DIR = os.path.join(PROJECT_DIR, "keys")
PRIV_KEY = os.path.join(KEY_DIR, "ota_sign_key.pem")
PUB_KEY = os.path.join(KEY_DIR, "ota_pubkey.pem")
PUB_HEADER = os.path.join(PROJECT_DIR, "include", "ota_pubkey.h")

CURVE = "prime256v1"


def run(cmd):
    """Run an openssl command, returning stdout bytes; abort on failure."""
    proc = subprocess.run(cmd, capture_output=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr.decode("utf-8", "replace"))
        raise SystemExit("command failed: %s" % " ".join(cmd))
    return proc.stdout


def openssl():
    probe = subprocess.run(["openssl", "version"], capture_output=True)
    if probe.returncode != 0:
        raise SystemExit("openssl is required on PATH (keygen + signing)")


def write_pubkey_header():
    """Emit include/ota_pubkey.h from the public key PEM. Generated file - never
    edit by hand (same rule as webui_html_gz.h and the *_vlw.h font headers)."""
    if not os.path.exists(PUB_KEY):
        raise SystemExit("%s missing - run 'keygen' first" % PUB_KEY)
    pem = open(PUB_KEY, "r", encoding="utf-8").read().strip().splitlines()
    lines = "\n".join('  "%s\\n"' % ln for ln in pem)
    with open(PUB_HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "// GENERATED by scripts/ota_sign.py pubkey - do not edit by hand.\n"
            "// Public half of the OTA release signing keypair. Public by\n"
            "// design: it is what the firmware uses to verify pulled images.\n"
            "// Rotating it means every deployed unit stops accepting the old\n"
            "// key's releases, so a rotation must be shipped by USB flash.\n"
            "#pragma once\n\n"
            "static const char OTA_PUBKEY_PEM[] =\n"
            "%s\n"
            ";\n" % lines
        )
    print("[ota_sign] wrote %s" % os.path.relpath(PUB_HEADER, PROJECT_DIR))


def cmd_keygen():
    openssl()
    if os.path.exists(PRIV_KEY):
        raise SystemExit("%s already exists - refusing to overwrite.\n"
                         "Losing it means the units you already shipped can no\n"
                         "longer accept any new signed release over OTA." % PRIV_KEY)
    os.makedirs(KEY_DIR, exist_ok=True)
    run(["openssl", "ecparam", "-name", CURVE, "-genkey", "-noout",
         "-out", PRIV_KEY])
    run(["openssl", "pkey", "-in", PRIV_KEY, "-pubout", "-out", PUB_KEY])
    print("[ota_sign] private key : %s" % os.path.relpath(PRIV_KEY, PROJECT_DIR))
    print("[ota_sign] public key  : %s" % os.path.relpath(PUB_KEY, PROJECT_DIR))
    print("[ota_sign] BACK UP THE PRIVATE KEY OFFLINE. keys/ is gitignored on")
    print("[ota_sign] purpose - it must never enter the repository.")
    write_pubkey_header()


def cmd_pubkey():
    write_pubkey_header()


def build_payload(version, firmware):
    digest = hashlib.sha256(open(firmware, "rb").read()).digest()
    return digest + b"\n" + version.encode("utf-8"), digest


def cmd_sign(argv):
    openssl()
    if len(argv) < 2:
        raise SystemExit("usage: sign <version> <firmware.bin> [out.sig]")
    version, firmware = argv[0], argv[1]
    if not os.path.exists(firmware):
        raise SystemExit("no such file: %s" % firmware)
    if not os.path.exists(PRIV_KEY):
        raise SystemExit("%s missing - run 'keygen' first (or restore a backup)"
                         % PRIV_KEY)
    out = argv[2] if len(argv) > 2 else firmware + ".sig"
    payload, digest = build_payload(version, firmware)
    tmp_payload = out + ".payload"
    with open(tmp_payload, "wb") as f:
        f.write(payload)
    try:
        run(["openssl", "dgst", "-sha256", "-sign", PRIV_KEY,
             "-out", out, tmp_payload])
    finally:
        os.remove(tmp_payload)
    der = open(out, "rb").read()
    print("[ota_sign] firmware sha256 : %s" % digest.hex())
    print("[ota_sign] signed for      : version %s" % version)
    print("[ota_sign] signature (%dB): %s" % (len(der), out))
    print("[ota_sign] upload this file as the release asset '%s'"
          % os.path.basename(out))


def cmd_verify(argv):
    openssl()
    if len(argv) < 2:
        raise SystemExit("usage: verify <version> <firmware.bin> [sig]")
    version, firmware = argv[0], argv[1]
    sigfile = argv[2] if len(argv) > 2 else firmware + ".sig"
    for path in (firmware, sigfile):
        if not os.path.exists(path):
            raise SystemExit("no such file: %s" % path)
    sig = open(sigfile, "rb").read()
    if len(sig) < 8 or sig[0] != 0x30:
        raise SystemExit("signature file does not look like a DER ECDSA "
                         "signature (%d bytes)" % len(sig))
    payload, digest = build_payload(version, firmware)
    tmp_payload = sigfile + ".payload"
    open(tmp_payload, "wb").write(payload)
    try:
        proc = subprocess.run(["openssl", "dgst", "-sha256", "-verify", PUB_KEY,
                               "-signature", sigfile, tmp_payload],
                              capture_output=True)
        ok = proc.returncode == 0
    finally:
        os.remove(tmp_payload)
    if not ok:
        print(proc.stdout.decode("utf-8", "replace"))
        print(proc.stderr.decode("utf-8", "replace"))
        raise SystemExit("[ota_sign] VERIFY FAILED - firmware does not match "
                         "the signature for version %s" % version)
    print("[ota_sign] verified: %s for version %s" % (
        os.path.basename(firmware), version))


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    cmd, argv = sys.argv[1], sys.argv[2:]
    if cmd == "keygen":
        cmd_keygen()
    elif cmd == "pubkey":
        cmd_pubkey()
    elif cmd == "sign":
        cmd_sign(argv)
    elif cmd == "verify":
        cmd_verify(argv)
    else:
        raise SystemExit("unknown command: %s" % cmd)


if __name__ == "__main__":
    main()
