#!/usr/bin/env python3
"""Issue #21 verification (host-side replica).

Checks, straight from src/config.cpp, that
  1. every numeric parameter has a band and lo <= hi,
  2. no shipped default falls outside its own band (a default that gets clamped
     would log on every boot and silently change the shipped behaviour),
  3. every numeric value in FACTORY_DEFAULT_JSON falls inside the band,
  4. the cross-field rules that sanitizeConfigPairs() enforces hold for the
     shipped defaults (min < max, warn <= crit, satellite ramp, baud/CPU steps),
  5. the FIRMWARE_LIMITS table in src/webui.html matches the firmware bands
     exactly (it is generated by scripts/make_webui_limits.py).

Run from the repository root:  python scripts/verify_config_ranges.py
"""
import json
import re
import sys

SRC = "src/config.cpp"
num = r"[-+0-9.eEfF]+"
sym = r"[-+0-9.eEfFA-Z_]+"

header = open("src/dashboard.h", encoding="utf-8").read()
consts = {m.group(1): float(m.group(2))
          for m in re.finditer(r"constexpr\s+\w+\s+([A-Z0-9_]+)\s*=\s*([0-9.eE+]+)UL?;", header)}

text = open(SRC, encoding="utf-8").read()

call = re.compile(
    r"(?m)^\s*CFG_(INT|UINT|FLT)\(\s*([A-Z0-9_]+)\s*,\s*\"([^\"]+)\"\s*,\s*"
    r"(" + num + r")\s*,\s*(" + sym + r")\s*,\s*(" + sym + r")\s*\);", re.S)

rows = call.findall(text)
params = {}
errors = []


def resolve(expr):
    """Numeric literal, or a constexpr name from dashboard.h."""
    try:
        return float(expr.rstrip("f"))
    except ValueError:
        if expr in consts:
            return consts[expr]
        raise KeyError(expr)


for kind, name, nvs, dflt, lo, hi in rows:
    try:
        d, l, h = resolve(dflt), resolve(lo), resolve(hi)
    except KeyError as e:
        errors.append("%s: band references unknown constant %s" % (name, e))
        continue
    params[name] = (kind, d, l, h)
    if l > h:
        errors.append("%s: empty band [%g..%g]" % (name, l, h))
    if not (l <= d <= h):
        errors.append("%s: default %g outside its band [%g..%g]" % (name, d, l, h))

print("numeric parameters with bands: %d" % len(rows))

# 3. factory defaults
fm = re.search(r'const char FACTORY_DEFAULT_JSON\[\] = R"\((\{.*?\})\)";', text,
                re.S)
factory = json.loads(fm.group(1))
band_notes = []
for key, val in factory.items():
    if isinstance(val, bool) or not isinstance(val, (int, float)):
        continue
    if key not in params:
        band_notes.append("%s: in factory JSON but no numeric band found" % key)
        continue
    _, d, l, h = params[key]
    if not (l <= float(val) <= h):
        errors.append("factory %s=%g outside band [%g..%g]" % (key, val, l, h))
print("factory JSON numeric keys checked: %d" %
      sum(1 for v in factory.values()
          if isinstance(v, (int, float)) and not isinstance(v, bool)))

# the shipped (compiled-in) defaults are the same values, but check the ones
# the cross-field rules touch directly
def val(name):
    return params[name][1]

pairs = [
    ("TEMP_BAR_MIN < TEMP_BAR_MAX", val("TEMP_BAR_MIN") < val("TEMP_BAR_MAX")),
    ("TEMP_WARN_YEL <= TEMP_WARN_RED", val("TEMP_WARN_YEL") <= val("TEMP_WARN_RED")),
    ("FUEL_WARN_RED <= FUEL_WARN_YEL",
     val("FUEL_WARN_RED") <= val("FUEL_WARN_YEL")),
    ("LIGHT_SENSOR_DARK < BRIGHT",
     val("LIGHT_SENSOR_DARK_VAL") < val("LIGHT_SENSOR_BRIGHT_VAL")),
    ("MIN_SATELLITES <= OPTIMAL_SATELLITES",
     val("MIN_SATELLITES") <= val("OPTIMAL_SATELLITES")),
    ("CPU_THROTTLE_TEMP_WARN <= CRIT",
     val("CPU_THROTTLE_TEMP_WARN") <= val("CPU_THROTTLE_TEMP_CRIT")),
]
for label, ok in pairs:
    if not ok:
        errors.append("cross-field rule failed: " + label)

BAUDS = {1200, 2400, 4800, 9600, 19200, 38400, 57600, 74400, 115200, 230400,
         460800, 921600}
if int(val("GPS_BAUD")) not in BAUDS:
    errors.append("GPS_BAUD default %g is not a standard rate" % val("GPS_BAUD"))
if int(val("MANUAL_CPU_FREQ")) not in {80, 160, 240}:
    errors.append("MANUAL_CPU_FREQ default %g is not a supported clock"
                  % val("MANUAL_CPU_FREQ"))

# 4. the WebUI mirror must match the firmware exactly: a drifted band would make
#    the form show (or correct to) limits the device does not actually enforce.
ui = open("src/webui.html", encoding="utf-8").read()
m = re.search(r"// BEGIN FIRMWARE_LIMITS.*?const FIRMWARE_LIMITS = "
              r"\{(.*?)\};.*?// END FIRMWARE_LIMITS", ui, re.S)
if not m:
    errors.append("src/webui.html has no FIRMWARE_LIMITS block "
                  "(run scripts/make_webui_limits.py)")
else:
    ui_rows = {}
    for name, lo, hi in re.findall(
            r"([A-Z0-9_]+):\s*\[([-0-9.eE+]+),\s*([-0-9.eE+]+)\],", m.group(1)):
        ui_rows[name] = (float(lo), float(hi))
    print("WebUI FIRMWARE_LIMITS entries: %d" % len(ui_rows))
    for name in sorted(set(params) - set(ui_rows)):
        errors.append("%s: band missing from the WebUI table" % name)
    for name in sorted(set(ui_rows) - set(params)):
        errors.append("%s: in the WebUI table but has no band in config.cpp"
                      % name)
    for name in sorted(set(ui_rows) & set(params)):
        band = (params[name][2], params[name][3])
        if ui_rows[name] != band:
            errors.append("%s: WebUI band %s does not match firmware band %s"
                          % (name, ui_rows[name], band))

# parameters that a snapshot of the WebUI can post: every numeric factory key must
# also be present in the band table (a missing band means an unvalidated hole)
for note in band_notes:
    print("note:", note)

if errors:
    print("\nFAIL")
    for e in errors:
        print(" -", e)
    sys.exit(1)
print("\nOK: every numeric parameter is band-checked, defaults are in band, "
      "cross-field rules hold")
