# Prebuild script: converts all Fonts/*.vlw files into PROGMEM headers
# in include/*.h. This allows LovyanGFX to stream antialiased vector VLW fonts
# directly from Flash memory (PROGMEM) without file I/O overhead or DRAM allocation.
import os

def convert_vlw_files(project_dir):
    fonts_dir = os.path.join(project_dir, "Fonts")
    include_dir = os.path.join(project_dir, "include")

    if not os.path.exists(fonts_dir):
        print("[convert_vlw] %s not found, skipping" % fonts_dir)
        return

    for fname in os.listdir(fonts_dir):
        if not fname.endswith(".vlw"):
            continue

        src_vlw = os.path.join(fonts_dir, fname)
        base_name = fname[:-4].replace("-", "_")
        hdr_name = base_name + "_vlw.h"
        hdr_path = os.path.join(include_dir, hdr_name)

        with open(src_vlw, "rb") as f:
            data = f.read()

        var_name = base_name + "_vlw"
        len_name = base_name + "_vlw_len"

        with open(hdr_path, "w", encoding="utf-8") as f:
            f.write("// Auto-generated by scripts/vlw_to_header.py - do not edit.\n")
            f.write("#pragma once\n")
            f.write("#include <pgmspace.h>\n")
            f.write("#include <stdint.h>\n\n")
            f.write("const uint8_t %s[] PROGMEM = {\n  " % var_name)
            for i, b in enumerate(data):
                if i % 16 == 0 and i != 0:
                    f.write("\n  ")
                f.write("0x%02X," % b)
            f.write("\n};\n\n")
            f.write("const uint32_t %s = %d;\n" % (len_name, len(data)))

        print("[convert_vlw] %s (%d bytes) -> %s" % (fname, len(data), hdr_name))

try:
    Import("env")
    p_dir = env.subst("$PROJECT_DIR")
    convert_vlw_files(p_dir)
except NameError:
    p_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    convert_vlw_files(p_dir)
