# Prebuild script: converts Fonts/DS-DIGIT_120px.vlw into a PROGMEM header
# file (include/DS_DIGIT_120px_vlw.h). This allows LovyanGFX to stream 120px speed
# glyphs directly from Flash memory without allocating a ~45KB buffer in DRAM.
import os

def convert_vlw(project_dir):
    src_vlw = os.path.join(project_dir, "Fonts", "DS-DIGIT_120px.vlw")
    hdr_path = os.path.join(project_dir, "include", "DS_DIGIT_120px_vlw.h")

    if not os.path.exists(src_vlw):
        print("[convert_vlw] %s not found, skipping" % src_vlw)
        return

    with open(src_vlw, "rb") as f:
        data = f.read()

    with open(hdr_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/vlw_to_header.py - do not edit.\n")
        f.write("#pragma once\n")
        f.write("#include <pgmspace.h>\n")
        f.write("#include <stdint.h>\n\n")
        f.write("const uint8_t DS_DIGIT_120px_vlw[] PROGMEM = {\n  ")
        for i, b in enumerate(data):
            if i % 16 == 0 and i != 0:
                f.write("\n  ")
            f.write("0x%02X," % b)
        f.write("\n};\n\n")
        f.write("const uint32_t DS_DIGIT_120px_vlw_len = %d;\n" % len(data))

    print("[convert_vlw] VLW font %d bytes converted to PROGMEM header -> %s" % (len(data), hdr_path))

try:
    Import("env")
    p_dir = env.subst("$PROJECT_DIR")
    convert_vlw(p_dir)
except NameError:
    p_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    convert_vlw(p_dir)
