// GENERATED by scripts/ota_sign.py pubkey - do not edit by hand.
// Public half of the OTA release signing keypair. Public by
// design: it is what the firmware uses to verify pulled images.
// Rotating it means every deployed unit stops accepting the old
// key's releases, so a rotation must be shipped by USB flash.
#pragma once

static const char OTA_PUBKEY_PEM[] =
  "-----BEGIN PUBLIC KEY-----\n"
  "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEz4rPSz7xpMEC7CVb5q4hSzu2NDC3\n"
  "91UMaqfaZI80HHks8iY+fwRG1N1oYJBfHnzR2SNOsfAnIC3k821I4ljOcA==\n"
  "-----END PUBLIC KEY-----\n"
;
