#include "otasign.h"
#include "ota_pubkey.h"  // generated by scripts/ota_sign.py - do not hand-edit
#include <string.h>
#include <mbedtls/pk.h>
#include <mbedtls/sha256.h>

// Fail at build time instead of discovering at pull time that the framework's
// mbedTLS was compiled without what verification needs.
#if !defined(MBEDTLS_ECDSA_C) || !defined(MBEDTLS_PK_C) || !defined(MBEDTLS_PK_PARSE_C)
#error "OTA signature verification needs mbedTLS ECDSA + PK parse (MBEDTLS_ECDSA_C / MBEDTLS_PK_PARSE_C)"
#endif
#if !defined(MBEDTLS_ECP_DP_SECP256R1_ENABLED)
#error "OTA signature verification needs the P-256 curve (MBEDTLS_ECP_DP_SECP256R1_ENABLED)"
#endif

namespace {
// One streaming hash context, reused by the pull download. Static on purpose:
// the pull task must not heap-allocate in the middle of a flash write, and the
// context is only touched by that single task while a download is open.
mbedtls_sha256_context g_sha;
bool g_shaOpen = false;
}  // namespace

bool otaSigningAvailable() { return OTA_PUBKEY_PEM[0] != 0; }

void otaImageHashBegin() {
  if (g_shaOpen) {
    mbedtls_sha256_free(&g_sha);
    g_shaOpen = false;
  }
  mbedtls_sha256_init(&g_sha);
  if (mbedtls_sha256_starts(&g_sha, 0 /* SHA-256, not SHA-224 */) == 0)
    g_shaOpen = true;
}

bool otaImageHashUpdate(const uint8_t *data, size_t len) {
  if (!g_shaOpen || !data || !len) return false;
  return mbedtls_sha256_update(&g_sha, data, len) == 0;
}

bool otaImageHashFinish(uint8_t digest[32]) {
  if (!g_shaOpen || !digest) return false;
  int rc = mbedtls_sha256_finish(&g_sha, digest);
  mbedtls_sha256_free(&g_sha);
  g_shaOpen = false;
  return rc == 0;
}

bool otaVerifyImage(const uint8_t digest[32], const char *version,
                    const uint8_t *sigDer, size_t sigLen, int *mbedtlsErr) {
  if (mbedtlsErr) *mbedtlsErr = 0;
  if (!otaSigningAvailable() || !digest || !version || !sigDer) return false;
  if (sigLen == 0 || sigLen > OTA_SIG_MAX_LEN) return false;

  // Rebuild the exact signed payload: 32-byte image digest, 0x0A, version.
  // The version fields in the pull path are char[32], so 31 chars max; a
  // longer string means a caller bug, and guessing here would silently change
  // what is being verified.
  size_t vlen = strlen(version);
  if (vlen == 0 || vlen > 31) return false;
  uint8_t payload[32 + 1 + 31];
  memcpy(payload, digest, 32);
  payload[32] = 0x0A;
  memcpy(payload + 33, version, vlen);

  uint8_t hash[32];
  if (mbedtls_sha256(payload, 33 + vlen, hash, 0) != 0) return false;

  mbedtls_pk_context pk;
  mbedtls_pk_init(&pk);
  int rc = mbedtls_pk_parse_public_key(&pk,
                                       reinterpret_cast<const unsigned char *>(
                                           OTA_PUBKEY_PEM),
                                       strlen(OTA_PUBKEY_PEM) + 1);
  if (rc == 0)
    rc = mbedtls_pk_verify(&pk, MBEDTLS_MD_SHA256, hash, sizeof(hash),
                           sigDer, sigLen);
  mbedtls_pk_free(&pk);

  if (mbedtlsErr) *mbedtlsErr = rc;
  return rc == 0;
}
